@startuml

class TestSetManager {
    register-status-listener($status-listener)
    register-test-set-listener($test-set-listener)
    add-test-suite(:$test-set-id, :$ci-platform-identifier, :@tests)
    ..
    trigger-process-worklist()
    !process-worklist()
    ..
    new-pr-test-set(:$project, :$pr-number, :$commit-sha, :$commit-url, :$git-url)
    new-main-branch-test-set(:$project, :$commit-sha, :$commit-url, :$git-url)
    ..
    get-all-test-status-test-sets()
    ciplatform-tests-finished(:$test-set-id)
    update-test-status(:$test-set-id, :$ci-platform-identifier, :$test-id)
}

note top of TestSetManager
    Guides the test process. Makes sure
    no test set is either forgotten or
    evaluated multiple times.
end note

note right of TestSetManager::ciplatform-tests-finished
    to be called by a CiPlatform once its tests for a test set
    are all done
end note


class SourceArchiveCreator {
    create-archive(:$source-spec --> :$source-archive-id)
}


class SourceSpec {
    has $rakudo-repo
    has $rakudo-commit-sha
    has $nqp-repo
    has $nqp-commit-sha
    has $moar-repo
    has $moar-commit-sha
}

SourceSpec --> SourceArchiveCreator


note top of SourceArchiveCreator
    Creates source archives and provides
    access to them. Makes sure no source
    state is created more than once.
end note


interface TestSetListener {
    new-test-set(:$test-set-id, :$source-archive-id)
}

TestSetListener --> TestSetManager


interface CiPlatform {
    !process-new-tests()
    !trigger-process-running-tests()
    !process-running-tests()
}
CiPlatform --|> TestSetListener

note top of CiPlatform
    Each subclass instance corresponds to
    one CI platform. Queues tests on
    the platform and retrieves results.
end note
note right of CiPlatform::trigger-process-running-tests
    to be called periodically by a timer
end note


class ObsCiPlatformConnector {
    process-hook()
}
ObsCiPlatformConnector --|> CiPlatform

note top of ObsCiPlatformConnector: Implementation of CiPlatformConnector


class AzureCiPlatformConnector {
    process-hook()
}
AzureCiPlatformConnector --|> CiPlatform

note top of AzureCiPlatformConnector: Implementation of CiPlatformConnector


interface StatusListener {
    tests-queued(:$test-set-id, :@tests)
    test-status-changed(:$test-set-id, :$test-id, :$status)
}

StatusListener --> TestSetManager

note top of StatusListener
    Implementers can receive status
    change events from the `TestSetManager`
end note


class GithubTestRequester {
    new-re-test-command(:$project, :$pr-number, :$comment-id, :$user-url)
    process-hook(:$request)
    !determine-source-spec(:$project, :$repo, :$commit-sha --> SourceSpec)
}

GithubTestRequester --|> StatusListener

@enduml
