@startuml
participant CroRouter            As cr
participant GitHubTestRequester  As gtr
participant TestSetManager       As tsm
participant SourceArchiveCreator As sac
participant AzureCiPlatform      As acp
participant ObsCiPlatform        As ocp

== New Commit ==

[-> cr: notification from GitHub
activate cr

cr -> gtr: process-hook()
activate gtr

note over gtr
    add request to work list,
    call trigger-process-worklist()
    which instantly returns
end note

return

deactivate cr

== GitHubTestRequester.process-worklist() ==

note over gtr
Triggered in regular intervals and at each process-hook() call.
end note

gtr -> gtr: process-worklist()
activate gtr

gtr -> gtr: determine-source-spec()
activate gtr
[<-> gtr: retrieve repo infos
return

gtr -> tsm: new-main-branch-test-set()
activate tsm

note over tsm
    add request to work list,
    call trigger-process-worklist()
    which instantly returns
end note

return


deactivate gtr

== TestSetManager.process-worklist() ==

note over tsm
    Triggered in regular intervals and at each process-hook() call.
end note

tsm -> tsm: process-worklist()
activate tsm

opt status == new
    tsm -> sac: create-archive()
    activate sac
        note over sac
            Acts on a set of local git repos
            - Add remotes if they are missing
            - fetch
            - checkout requested commits
            - bundles archive
        end note
    return
    note over tsm: set status = source-archive-created
end
opt status == source-archive-created

    tsm -> ocp: new-test-set()
    activate ocp
        note over ocp
            add item to work list,
            call trigger-process-worklist()
            which instantly returns
        end note
    return

    tsm -> acp: new-test-set()
    activate acp
        note over acp
            add item to work list,
            call trigger-process-worklist()
            which instantly returns
        end note
    return

    note over tsm: set status = waiting-for-test

end

deactivate tsm

== ObsCiPlatform.process-worklist() ==

note over ocp
Triggered in regular intervals and at each process-hook() call.
end note

ocp -> ocp: process-worklist()
activate ocp

]<- ocp: send test requests to OBS

]<-> ocp: retrieve tests in suite from OBS

ocp -> tsm: add-test-suite()
activate tsm

tsm -> gtr: test-suite-queued()
activate gtr
note over gtr: Add item to worklist
return

return

deactivate ocp

== OBS test status changed ==

[-> cr: notification from OBS
activate cr

    cr -> ocp: process-hook()
    activate ocp

        ocp -> tsm: update-test-status()
        activate tsm

            tsm -> gtr: test-status-changed()
            activate gtr
                note over gtr: Add item to worklist
            return
            
            opt all tests are done
                note over tsm: set status = done
            end

        return

    return

deactivate cr

@enduml
